@startuml
title: Module Graph with added module
package "Module Path" {

  [my.starter.module] as starter #lime
  [another.module] as unused #lime
  starter --> [java.base]: requires
  starter --> [my.core.module]: requires
  [my.core.module] --> [java.base]: requires
  [my.infra.module] --> [java.base]: requires
  [my.core.module] --> [my.infra.module]: uses
}
note top of unused: --add-modules=another.module
note top of starter: application root
@enduml